// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EducationPlatformDBContext))]
    [Migration("20260725103935_AddCouponStudentAndUserOtpIndexes")]
    partial class AddCouponStudentAndUserOtpIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AcademicManagement.Aggregate.Grade", b =>
                {
                    b.Property<Guid>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GradeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Domain.AcademicManagement.Aggregate.Subject", b =>
                {
                    b.Property<Guid>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("SubjectID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.AcademicManagement.Entity.DefaultLesson", b =>
                {
                    b.Property<Guid>("DefaultLessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("GradeID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectID1")
                        .HasColumnType("uuid");

                    b.HasKey("DefaultLessonID");

                    b.HasIndex("GradeID");

                    b.HasIndex("SubjectID1");

                    b.HasIndex("SubjectID", "GradeID");

                    b.ToTable("DefaultLessons");
                });

            modelBuilder.Entity("Domain.AuditManagement.Aggregate.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.HasKey("ComplaintID");

                    b.HasIndex("CourseID");

                    b.HasIndex("Status");

                    b.HasIndex("StudentID");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("GradeID")
                        .HasColumnType("uuid");

                    b.Property<string>("LearningOutcomes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CourseID");

                    b.HasIndex("GradeID");

                    b.HasIndex("Status");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Policy", b =>
                {
                    b.Property<Guid>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PolicyID");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("LessonID");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Chapter", b =>
                {
                    b.Property<Guid>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsViolated")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ChapterID");

                    b.HasIndex("CourseID");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.CourseReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("CourseReviews");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Lesson", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("LessonID");

                    b.HasIndex("ChapterID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Material", b =>
                {
                    b.Property<Guid>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("MaterialID");

                    b.HasIndex("LessonID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.PolicyRule", b =>
                {
                    b.Property<Guid>("PolicyRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyID")
                        .HasColumnType("uuid");

                    b.HasKey("PolicyRuleID");

                    b.HasIndex("PolicyID");

                    b.ToTable("PolicyRules");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Quiz", b =>
                {
                    b.Property<Guid>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("QuizID");

                    b.HasIndex("LessonID");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.ViolatedPolicy", b =>
                {
                    b.Property<Guid>("ViolatedPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyID")
                        .HasColumnType("uuid");

                    b.HasKey("ViolatedPolicyID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PolicyID");

                    b.ToTable("ViolatedPolicies");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Aggregate.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("Status");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.ChapterProgress", b =>
                {
                    b.Property<Guid>("ChapterProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseProgressID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("ChapterProgressID");

                    b.HasIndex("ChapterID");

                    b.HasIndex("CourseProgressID");

                    b.ToTable("ChapterProgresses");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.CourseProgress", b =>
                {
                    b.Property<Guid>("CourseProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CompletionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("EnrollmentID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CourseProgressID");

                    b.HasIndex("EnrollmentID")
                        .IsUnique();

                    b.ToTable("CourseProgresses");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.LessonProgress", b =>
                {
                    b.Property<Guid>("LessonProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterProgressID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("uuid");

                    b.HasKey("LessonProgressID");

                    b.HasIndex("ChapterProgressID");

                    b.HasIndex("LessonID");

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.QuizProgress", b =>
                {
                    b.Property<Guid>("QuizProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonProgressID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizID")
                        .HasColumnType("uuid");

                    b.HasKey("QuizProgressID");

                    b.HasIndex("LessonProgressID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizProgresses");
                });

            modelBuilder.Entity("Domain.IdentityManagement.Aggregate.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmailOtp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailOtpExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailOtp");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Coupon", b =>
                {
                    b.Property<Guid>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("CouponID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StudentID");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlatformAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TeacherAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CourseID");

                    b.HasIndex("Status");

                    b.HasIndex("StudentID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Penalty", b =>
                {
                    b.Property<Guid>("PenaltyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uuid");

                    b.HasKey("PenaltyID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Domain.AcademicManagement.Entity.DefaultLesson", b =>
                {
                    b.HasOne("Domain.AcademicManagement.Aggregate.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.AcademicManagement.Aggregate.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.AcademicManagement.Aggregate.Subject", null)
                        .WithMany("DefaultLessons")
                        .HasForeignKey("SubjectID1");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Complaint", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.IdentityManagement.Aggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Course", b =>
                {
                    b.HasOne("Domain.AcademicManagement.Aggregate.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.AcademicManagement.Aggregate.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.IdentityManagement.Aggregate.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.CourseManagement.ValueObject.CoursePrice", "Price", b1 =>
                        {
                            b1.Property<Guid>("CourseID")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("PriceAmount");

                            b1.HasKey("CourseID");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseID");
                        });

                    b.Navigation("Grade");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Assignment", b =>
                {
                    b.HasOne("Domain.CourseManagement.Entity.Lesson", null)
                        .WithMany("Assignments")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Chapter", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", null)
                        .WithMany("Chapters")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.CourseReview", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.IdentityManagement.Aggregate.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Lesson", b =>
                {
                    b.HasOne("Domain.CourseManagement.Entity.Chapter", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Material", b =>
                {
                    b.HasOne("Domain.CourseManagement.Entity.Lesson", null)
                        .WithMany("Materials")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.PolicyRule", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Policy", null)
                        .WithMany("PolicyRules")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Quiz", b =>
                {
                    b.HasOne("Domain.CourseManagement.Entity.Lesson", null)
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.CourseManagement.ValueObject.QuizAnswer", "Answer", b1 =>
                        {
                            b1.Property<Guid>("QuizID")
                                .HasColumnType("uuid");

                            b1.Property<string>("CorrectAnswers")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CorrectAnswers");

                            b1.Property<string>("Options")
                                .HasColumnType("text")
                                .HasColumnName("Options");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("AnswerType");

                            b1.HasKey("QuizID");

                            b1.ToTable("Quizzes");

                            b1.WithOwner()
                                .HasForeignKey("QuizID");
                        });

                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.ViolatedPolicy", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", null)
                        .WithMany("ViolatedPolicies")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CourseManagement.Aggregate.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Aggregate.Enrollment", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.ChapterProgress", b =>
                {
                    b.HasOne("Domain.CourseManagement.Entity.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.EnrollmentManagement.Entity.CourseProgress", null)
                        .WithMany("ChapterProgresses")
                        .HasForeignKey("CourseProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.CourseProgress", b =>
                {
                    b.HasOne("Domain.EnrollmentManagement.Aggregate.Enrollment", null)
                        .WithOne("CourseProgress")
                        .HasForeignKey("Domain.EnrollmentManagement.Entity.CourseProgress", "EnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.LessonProgress", b =>
                {
                    b.HasOne("Domain.EnrollmentManagement.Entity.ChapterProgress", null)
                        .WithMany("LessonProgresses")
                        .HasForeignKey("ChapterProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CourseManagement.Entity.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.QuizProgress", b =>
                {
                    b.HasOne("Domain.EnrollmentManagement.Entity.LessonProgress", null)
                        .WithMany("QuizProgresses")
                        .HasForeignKey("LessonProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CourseManagement.Entity.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Domain.IdentityManagement.Aggregate.User", b =>
                {
                    b.OwnsOne("Domain.IdentityManagement.ValueObject.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserID")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserID");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserID");
                        });

                    b.OwnsOne("Domain.IdentityManagement.ValueObject.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserID")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RefreshTokenExpiresAt");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("RefreshTokenHash");

                            b1.HasKey("UserID");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserID");
                        });

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Coupon", b =>
                {
                    b.HasOne("Domain.IdentityManagement.Aggregate.User", null)
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Order", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.IdentityManagement.Aggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.OrderManagement.Aggregate.Penalty", b =>
                {
                    b.HasOne("Domain.CourseManagement.Aggregate.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.IdentityManagement.Aggregate.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.AcademicManagement.Aggregate.Subject", b =>
                {
                    b.Navigation("DefaultLessons");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ViolatedPolicies");
                });

            modelBuilder.Entity("Domain.CourseManagement.Aggregate.Policy", b =>
                {
                    b.Navigation("PolicyRules");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.CourseManagement.Entity.Lesson", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Materials");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Aggregate.Enrollment", b =>
                {
                    b.Navigation("CourseProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.ChapterProgress", b =>
                {
                    b.Navigation("LessonProgresses");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.CourseProgress", b =>
                {
                    b.Navigation("ChapterProgresses");
                });

            modelBuilder.Entity("Domain.EnrollmentManagement.Entity.LessonProgress", b =>
                {
                    b.Navigation("QuizProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
